# render.yaml
services:
  # Backend API Service
  - type: web
    name: documents-app-api
    env: node
    repo: https://github.com/agoley/DocsClone # Update this if it's not correct
    branch: render-bootstrapping # Explicit branch to deploy from
    buildCommand: cd server && npm install
    startCommand: cd server && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: API_ONLY
        value: "true"
      - key: CORS_ORIGIN
        fromService:
          name: documents-app-frontend
          type: web
          property: url
    plan: free

  # Frontend Static Site Service
  - type: web
    name: documents-app-frontend
    env: static
    buildCommand: chmod +x ./client-build-debug.sh && ./client-build-debug.sh
    staticPublishPath: client/build # Removed the leading ./ which can cause issues
    repo: https://github.com/agoley/DocsClone # Update this if it's not correct
    branch: render-bootstrapping # Explicit branch to deploy from
    buildCommand: cd client && npm install && npm run build
    publishDir: client/build
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          name: documents-app-api
          type: web
          property: url
      - key: NODE_ENV
        value: production
    headers:
      - path: /*
        name: Cache-Control
        value: no-store
