services:
  - type: web
    name: documents-app-backend
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && node server.js
    branch: render-bootstrapping
    envVars:
      - key: NODE_ENV
        value: production
    plan: free
