# render.yaml
services:
  - type: web
    name: documents-app-backend
    env: node
    repo: https://github.com/agoley/DocsClone # Update this if it's not correct
    branch: render-bootstrapping # Explicit branch to deploy from
    buildCommand: chmod +x ./build.sh && ./build.sh
    startCommand: cd server && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: CI
        value: "false"
    plan: free
